### ISSUE TITLE
No adapter removal despite Adapter Content Fail in FastQC report

### ISSUE THREAD

**Issue by nnordhol** [iquasere/MOSCA#13]
Hi, 

Nice to see you were able to integrate the MT only-mode in 1.3.
The preprocessing would fail to recognise that adapters were present (as reported by FastQC) and skip adapter removal. I think I identified the problem in preprocess.py: the has_adapter() function checks for over represented sequences when it should check for "Adapter Content" in the FastQC report. Changing the function as below solved it for me and would be the correct way to identify whether adapters are present from FastQC report:

def has_adapters(self, fastqc_report):
        data = parse_fastqc(fastqc_report)
        if data['Adapter Content'][0] == 'pass':
            return False
        else:
            return True

Best,
Niclas

**Comment by iquasere** [comment]
Hey there! Yes, finally can submit MT alone, although much fine tuning is still required on that workflow... 

This error you point to is in fact an oversight on my part, I guess the datasets with adapters I used at the time all had overrepresented sequences and I missed the adapter content part. The best fix would be to expand the ```has_adapters``` function to include your method. The "overrepresented sequences" module should still be considered because sometimes the "adapter content" module doesn't catch the adapters, but they appear on "overrepresented sequences", and identified in the description. I will welcome a pull request to MOSCA, otherwise a fix will come in the next version ^^
