### ISSUE TITLE
Snakefile KeyError for 'split_gene_calling'

### ISSUE THREAD

**Issue by ssorgatem** [iquasere/MOSCA#19]
Trying to use MOSCA 2.0 I get this error:

KeyError in file /local_usr/lib/miniconda3/envs/mosca/share/MOSCA/Snakefile, line 197:
'split_gene_calling'

It seems to be looking for a split_gene_calling section in the config file, but I see no documentation on what to put there, ans MOSGUITO doesn't add it either.

**Comment by iquasere** [comment]
MOSGUITO still outputs parameters for MOSCA 1.6. In the meantime, you can add the following line to your config file: ```"split_gene_calling":4,``` - do notice the comma. This paramters tells MOSCA to break the result of gene calling into enough parts for DIAMOND to be capable of handling that data. It's a new parameter, included because in the latest versions of DIAMOND it leaks data to the disk, and fills it too much.

**Comment by ssorgatem** [comment]
If I do that I get this error:

TypeError in file /usr/local/illumina/local_usr/lib/miniconda3/envs/mosca/share/MOSCA/Snakefile, line 227:
'str' object cannot be interpreted as an integer


Changing it to "4", without the comma, seems to start the analysis... let's see until what point.

**Comment by ssorgatem** [comment]
Also apparently yaml config files don't work unless I remove the 'ensure_ascii=False,' from line 45 in mosca.py.

It didn't run for long, I attach the log and the config file, because I can't figure out what's wrong:

log file: https://pastebin.com/3qU32jnp
config: https://pastebin.com/0xnFQ670

**Comment by iquasere** [comment]
Sorry for taking so long to follow up, had to dedicate myself to other projects. 

I see that your YAML has both string-type and number-type values in, for example, KEGGCharter maps. I think the problem you are seeing is not related to the ```split_gene_calling``` parameter, which must be a number. Rather, it is these invalid values. I also see that values for UPIMAPI columns are not enclosed in plicas (```'```), which might cause problems since they have spaces. I would suggest using [MOSGUITO](https://iquasere.github.io/MOSGUITO) to obtain a JSON formatted config file for MOSCA, but do not it also still doesn't bring the ```split_gene_calling``` parameter, which must be inputted manually.

We are working on a web version of MOSCA that will make it much easier to run it. Also, I'm soon updating MOSGUITO to correctly produce the configuration files for MOSCA. For now, try to use it, and please do report back if you still find problems.
