### ISSUE TITLE
Parameter from config.json not recognized.

### ISSUE THREAD

**Issue by Ayala-Ruan-CesarM** [iquasere/MOSCA#22]
Hi,
I am trying to run the full MOSCA pipeline for a metra-transcriptome differencial expressión analyzsis. 
I created the config file with MOSQUITO. However, when I change the value of "minimum_read_length" from 100 (default) to 50 (as my reads are 76 pb long), the trimmomatic process althougt runs without problems it outputs empty fastq files that can not be parsed to the assembly phase.

I check the config.json file created in the /output_dir/ and has in  "minimum_mg_read_length" and  "minimum_mt_read_length" variables a value of "100". 

The only way I find to solve the problem was to change locally the "default_config.json" file in the path /root/miniconda3/envs/MOSCA/share/MOSCA . There I change both minimum_mg_read_length and minimum_mt_read_length values to 50 and now trimmomatic output non-empty file that enters the assembly phase.

Althougth I solve the problem it, I guess it should't work that way.

**Please complete the following information:**
 - OS: Ubuntu 22.04.3 LTS, WSL-2
 - Version of MOSCA: 2.3.0

Regards, 
Cesar Ayala

**Comment by iquasere** [comment]
Hi, Cesar! Sorry to hear you are having problems with MOSCA, and they are all entirely my fault.

MOSGUITO unfortunately hasn't been updated in a long time. Now, MOSCA provides different parameters for both "minimum_mg_read_length" and "minimum_mt_read_length" exactly because you might have shorter reads for MT, which you might want to used a different MINLEN for.

It would be better to use the default.json file as the starting file for MOSCA's configuration. Even better would be for me to fix MOSGUITO, but for now I don't have much time to take care of it. It will be my priority after I finish my PhD thesis, though!
