### ISSUE TITLE
Error in rule upimapi -Annotation error- 

### ISSUE THREAD

**Issue by Ayala-Ruan-CesarM** [iquasere/MOSCA#23]
Hi,

In a differential expresion analysis upimapi brokes down with the follwing error 
"ERR: [Entry name] is not a valid column name for ID mapping. For more information, check https://github.com/iquasere/UPIMAPI/tree/master#sometimes-the-return-fields-are-not-properly-updated"

As additional files I am uploading the config file being used, the log produce by sneakemake and the complete error displayed in the screen. 
[config.json](https://github.com/iquasere/MOSCA/files/14736929/config.json)
[MOSCA_log.txt](https://github.com/iquasere/MOSCA/files/14736930/MOSCA_log.txt)
[Screen_error.txt](https://github.com/iquasere/MOSCA/files/14736931/Screen_error.txt)

I would love to get a complete execution of the MOSCA software it shows so much value for analyzing my samples.

**Please complete the following information:**
 - OS: Ubuntu 22.04.3 LTS, WSL-2
 - Version of MOSCA: 2.3.0

Regards.

Cesar Ayala

**Comment by iquasere** [comment]
As I said in the other issue, might be better to just use the default.json file as the starting point for that. Actually, you can just specify the `experiments` field, if you are ok with the remaining default parameters.

The error you are getting is because `Entry name`, `Gene names` and `Gene ontology (GO)` fields of UniProt ID mapping have changed name, and `Taxonomic identifier (GENUS)` and `Taxonomic identifier (SPECIES)` fields of UPIMAPI have also been changed. If you specify no value on the `upimapi_columns` field of the `config.json`, it will use default values (from the `defualt_config.json`) and those are correctly named.

Again, problem of not updating MOSGUITO in a loooong time, which is inexcusable. Once I finish my PhD thesis (very soon, I hope) I will get to update MOSGUITO
