### ISSUE TITLE
self.bowtie2 not defined in assembly.py

### ISSUE THREAD

**Issue by bwu62** [iquasere/MOSCA#6]
In assembly.py, line 113, self.bowtie2 throws an error because bowtie2 was never defined. Seems like an easy error to catch that should have been obvious if this pipeline was tested at all.

**Comment by iquasere** [comment]
The pipeline was tested, but only at the time of publication. Since then, it received significant changes and should have been properly tested before deployment. These next days I will be attempting to solve this and all other problems you have been here reporting. Thank you, btw, for helping me with the debug of MOSCA!

**Comment by iquasere** [comment]
This should be fixed in this latest version

**Comment by iquasere** [comment]
This has been fixed in the latest version
