### ISSUE TITLE
Versioning / releases

### ISSUE THREAD

**Issue by d4straub** [iquasere/MOSCA#9]
Hi there,

I am looking into metatranscriptomics workflows and found yours. One major drawback I see is that you have no releases/versioning and therefore unnecessarily make reproducibility harder.

I was also wondering whether it is possible to use your pipeline with an existing metagenome assembly & annotation, the readme implies that there need to be MG and MT reads, did I understand that correctly?

Best wishes

**Comment by iquasere** [comment]
Greetings

The tool is undergoing the final stages of major development. With the KEGG Pathway and MP integrations almost over, the first true version of MOSCA should come out in the next two weeks. Also, it still should have some bugs, because of these major integrations. 

Finally, even though I have plans for that in the future, for now the tool only allows MG, MG/MT and MG/MP reads/spectra input. The workflow from assembly or assembly + annotation would only imply a later entry point in MOSCA, but this is something that will only be implemented after the first release.

When this is built in MOSCA, I will informe you here!

 Kind regards

**Comment by iquasere** [comment]
I'm closing this one, as it addresses two issues that are already closed. The versioning is already happening, with MOSCA at version 1.3.3 (1.3.4 coming out today).

About using an assembly as input, because of MOSCA's modular workflow, this should already be possible. It would require a small hack, putting the contigs file in the right place with the right name, but the rest of the workflow should pick up at the right spot. If you want to test this, please let me know, and I will provide the instructions to do so.
